template: |-
  {persona_instruction}

  # Task Instructions
  {task_instructions}

  ## Scoring Rubric
  {scoring_rubric}
  
  ## Input Format

  ### Query Format
  a single line user query under the header ## Query followed by a new line.

  ### Document Format
  a single line with 1 to 5 sentences under the header ## Document followed by a new line.

  ## Response Format 
  {response_format}
  
  ### Response Format Restrictions
  The response should be a single line of text that follows the Output Format exactly.

  # Example
  ## Query
  {example_query}

  ## Document
  {example_doc}

  ## Response
  {example_response}

  # Task

  ## Query
  {query}

  ## Document
  {document}

  ## Response
